// <auto-generated />
namespace Isa.Infrastructures.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixrelationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixrelationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201904202209582_fix-relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
